#****************************************************************
#* lite-manager                                                 *
#* NOTE: do not edit this file as it is automatically generated *
#****************************************************************

CONFIG_SGL_PANEL_PLATFORM = sdl2
CONFIG_SGL_PANEL_PIXEL_DEPTH = 32
CONFIG_SGL_BACKGROUND_COLOR = SGL_WHITE
CONFIG_SGL_PANEL_WIDTH = 800
CONFIG_SGL_PANEL_HEIGHT = 480
CONFIG_SGL_PANEL_BUFFER_LINE = 10
CONFIG_SGL_EVENT_QUEUE_SIZE = 64
CONFIG_SGL_COLOR16_SWAP = n
CONFIG_SGL_DEBUG = y
CONFIG_SGL_LOG_COLOR = y
CONFIG_SGL_LOG_LEVEL = 0
CONFIG_SGL_FONT = y
CONFIG_SGL_TEXT_UTF8 = n
CONFIG_SGL_USE_OBJ_ID = y
CONFIG_SGL_HEAP_ALGO = lwmem
CONFIG_SGL_FL_INDEX_MAX = 20
CONFIG_SGL_HEAP_MEMORY_SIZE = 20
CONFIG_SGL_FONT_SONG23 = y
CONFIG_SGL_FONT_CONSOLAS23 = y

# Variables provided for Makefile
C_SOURCE := main.c ../../source/core/sgl_core.c ../../source/core/sgl_log.c ../../source/core/sgl_math.c ../../source/core/sgl_event.c ../../source/mm/lwmem/lwmem.c ../../source/mm/lwmem/mem.c ../../source/draw/sgl_draw_task.c ../../source/draw/sgl_draw_line.c ../../source/draw/sgl_draw_rect.c ../../source/draw/sgl_draw_bar.c ../../source/draw/sgl_draw_circle.c ../../source/draw/sgl_draw_text.c ../../source/draw/sgl_draw_border.c ../../source/draw/sgl_draw_ring.c \
            ../../source/widgets/line/sgl_line.c ../../source/widgets/button/sgl_button.c ../../source/widgets/slider/sgl_slider.c ../../source/widgets/label/sgl_label.c ../../source/fonts/sgl_ascii_song23.c ../../source/fonts/sgl_ascii_consolas23.c ../../source/port/sgl_port_sdl2.c test.c

C_PATH := -I/usr/include/SDL2 -I../../source -I../../source/include

C_DEFINE := -D_REENTRANT

C_FLAG :=  -g

LIB_NAME := -lSDL2

