#****************************************************************
#* lite-manager                                                 *
#* NOTE: do not edit this file as it is automatically generated *
#****************************************************************

CONFIG_SGL_PANEL_PIXEL_DEPTH = 16
CONFIG_SGL_EVENT_QUEUE_SIZE = 32
CONFIG_SGL_DIRTY_AREA_THRESHOLD = 64
CONFIG_SGL_DRAW_USE_DMA = n
CONFIG_SGL_COLOR16_SWAP = n
CONFIG_SGL_ANIMATION = n
CONFIG_SGL_ANIMATION_TICK_MS = n
CONFIG_SGL_DEBUG = y
CONFIG_SGL_LOG_COLOR = y
CONFIG_SGL_LOG_LEVEL = 0
CONFIG_SGL_TEXT_UTF8 = n
CONFIG_SGL_OBJ_USE_NAME = n
CONFIG_SGL_USE_STYLE_UNIFIED_API = y
CONFIG_SGL_HEAP_ALGO = lwmem
CONFIG_SGL_FL_INDEX_MAX = 20
CONFIG_SGL_HEAP_MEMORY_SIZE = 6000
CONFIG_SGL_FONT_SONG23 = y
CONFIG_SGL_FONT_CONSOLAS23 = n
CONFIG_SGL_FONT_KAI33 = n

# Variables provided for Makefile
C_SOURCE := src/main.c src/stm32f10x_it.c src/tft.c src/syscall.c hal/STM32F10x_StdPeriph_Driver/src/misc.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c \
            hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c hal/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c hal/STM32F10x_StdPeriph_Driver/system_stm32f10x.c ../../source/core/sgl_core.c ../../source/core/sgl_log.c ../../source/core/sgl_math.c ../../source/core/sgl_event.c ../../source/core/sgl_anim.c ../../source/mm/lwmem/lwmem.c ../../source/mm/lwmem/sgl_mm.c ../../source/draw/sgl_draw_line.c ../../source/draw/sgl_draw_rect.c ../../source/draw/sgl_draw_bar.c ../../source/draw/sgl_draw_circle.c ../../source/draw/sgl_draw_arc.c ../../source/draw/sgl_draw_text.c ../../source/draw/sgl_draw_ring.c ../../source/draw/sgl_draw_icon.c ../../source/widgets/line/sgl_line.c ../../source/widgets/rectangle/sgl_rectangle.c ../../source/widgets/circle/sgl_circle.c ../../source/widgets/ring/sgl_ring.c ../../source/widgets/arc/sgl_arc.c ../../source/widgets/button/sgl_button.c ../../source/widgets/slider/sgl_slider.c ../../source/widgets/label/sgl_label.c ../../source/widgets/switch/sgl_switch.c ../../source/widgets/msgbox/sgl_msgbox.c ../../source/widgets/textline/sgl_textline.c ../../source/widgets/textbox/sgl_textbox.c ../../source/widgets/checkbox/sgl_checkbox.c ../../source/widgets/listview/sgl_listview.c ../../source/widgets/icon/sgl_icon.c ../../source/widgets/numberkbd/sgl_numberkbd.c ../../source/fonts/sgl_ascii_song23.c

C_PATH := -Isrc -Ilib/cmsis -Ihal/STM32F10x_StdPeriph_Driver/inc -Ihal/STM32F10x_StdPeriph_Driver -I../../source -I../../source/include

C_DEFINE := -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER

ASM_SOURCE := src/startup_stm32f10x_md.S

LDS_SOURCE := stm32f1x_64KB_flash.ld

MC_FLAG :=  -mthumb -mcpu=cortex-m3 -march=armv7-m

AS_FLAG :=  -Wl, -Bstatic

C_FLAG :=  -O2 -Wl,-Bstatic -ffunction-sections -fdata-sections -ffreestanding  -g

LD_FLAG :=  -Wl,--cref -Wl,--no-relax -Wl,--gc-sections -ffreestanding -Wl,-Bstatic -Wl,--no-warn-rwx-segments -lc --specs=nano.specs

