//****************************************************************
//* lite-manager                                                 *
//* NOTE: do not edit this file as it is automatically generated *
//****************************************************************

#ifndef  __CONFIG_H__
#define  __CONFIG_H__


#define    CONFIG_SGL_PANEL_PIXEL_DEPTH       16
#define    CONFIG_SGL_EVENT_QUEUE_SIZE        32
#define    CONFIG_SGL_USE_STYLE_UNIFIED_API     1
#define    CONFIG_SGL_THEME_DEFAULT           1
#define    CONFIG_SGL_HEAP_ALGO               lwmem
#define    CONFIG_SGL_FL_INDEX_MAX            20
#define    CONFIG_SGL_HEAP_MEMORY_SIZE        4000
#define    CONFIG_SGL_FONT_SONG23             1


#endif  //!__CONFIG_H__
