//****************************************************************
//* lite-manager                                                 *
//* NOTE: do not edit this file as it is automatically generated *
//****************************************************************

#ifndef  __CONFIG_H__
#define  __CONFIG_H__


#define    CONFIG_SGL_PANEL_PIXEL_DEPTH       32
#define    CONFIG_SGL_EVENT_QUEUE_SIZE        16
#define    CONFIG_SGL_ANIMATION               1
#define    CONFIG_SGL_ANIMATION_TICK_MS       1
#define    CONFIG_SGL_DEBUG                   1
#define    CONFIG_SGL_LOG_COLOR               1
#define    CONFIG_SGL_LOG_LEVEL               0
#define    CONFIG_SGL_OBJ_USE_NAME            1
#define    CONFIG_SGL_USE_STYLE_UNIFIED_API     1
#define    CONFIG_SGL_THEME_DEFAULT           1
#define    CONFIG_SGL_HEAP_ALGO               lwmem
#define    CONFIG_SGL_FL_INDEX_MAX            20
#define    CONFIG_SGL_HEAP_MEMORY_SIZE        40960
#define    CONFIG_SGL_FONT_SONG23             1
#define    CONFIG_SGL_FONT_CONSOLAS23         1
#define    CONFIG_SGL_FONT_KAI33              1


#endif  //!__CONFIG_H__
